'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TAC.DNN.Modules.TAC_NPIinspectorSearch

    Partial Public Class View

        '''<summary>
        '''lblZipCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblZipCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblZipCode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblZipCode2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMainSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMainSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlMiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMiles As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdSearchZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSearchZip As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''lblStateText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStateText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCitySearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCitySearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCountySearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountySearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblStateText2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStateText2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlStateSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStateSearch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdSearchCCS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSearchCCS As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''lblResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResults As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dgSearchResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgSearchResults As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
